set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports pb_p_hr]
set_property IOSTANDARD LVCMOS33 [get_ports pb_s_min]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports setting]

set_property IOSTANDARD LVCMOS33 [get_ports {display[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {display_c[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_c[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_c[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_c[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[0]}]

set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN W19 [get_ports pb_p_hr]
set_property PACKAGE_PIN T17 [get_ports pb_s_min]
set_property PACKAGE_PIN V17 [get_ports rst]
set_property PACKAGE_PIN R2 [get_ports setting]

set_property PACKAGE_PIN V7 [get_ports {display[0]}]
set_property PACKAGE_PIN U7 [get_ports {display[1]}]
set_property PACKAGE_PIN V5 [get_ports {display[2]}]
set_property PACKAGE_PIN U5 [get_ports {display[3]}]
set_property PACKAGE_PIN V8 [get_ports {display[4]}]
set_property PACKAGE_PIN U8 [get_ports {display[5]}]
set_property PACKAGE_PIN W6 [get_ports {display[6]}]
set_property PACKAGE_PIN W7 [get_ports {display[7]}]

set_property PACKAGE_PIN U2 [get_ports {display_c[0]}]
set_property PACKAGE_PIN U4 [get_ports {display_c[1]}]
set_property PACKAGE_PIN V4 [get_ports {display_c[2]}]
set_property PACKAGE_PIN W4 [get_ports {display_c[3]}]

set_property PACKAGE_PIN L1 [get_ports {LEDs[15]}]
set_property PACKAGE_PIN P1 [get_ports {LEDs[14]}]
set_property PACKAGE_PIN N3 [get_ports {LEDs[13]}]
set_property PACKAGE_PIN P3 [get_ports {LEDs[12]}]
set_property PACKAGE_PIN U3 [get_ports {LEDs[11]}]
set_property PACKAGE_PIN W3 [get_ports {LEDs[10]}]
set_property PACKAGE_PIN V3 [get_ports {LEDs[9]}]
set_property PACKAGE_PIN V13 [get_ports {LEDs[8]}]
set_property PACKAGE_PIN V14 [get_ports {LEDs[7]}]
set_property PACKAGE_PIN U14 [get_ports {LEDs[6]}]
set_property PACKAGE_PIN U15 [get_ports {LEDs[5]}]
set_property PACKAGE_PIN W18 [get_ports {LEDs[4]}]
set_property PACKAGE_PIN V19 [get_ports {LEDs[3]}]
set_property PACKAGE_PIN U19 [get_ports {LEDs[2]}]
set_property PACKAGE_PIN E19 [get_ports {LEDs[1]}]
set_property PACKAGE_PIN U16 [get_ports {LEDs[0]}]