set_property IOSTANDARD LVCMOS33 [get_ports f_crystal]
set_property IOSTANDARD LVCMOS33 [get_ports f_out]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN W5 [get_ports f_crystal]
set_property PACKAGE_PIN U16 [get_ports f_out]
set_property PACKAGE_PIN V17 [get_ports rst]
